import type { Sound } from './types'

export const SOUNDS: Sound[] = [
  {
    id: 'rain',
    name: 'Rain',
    emoji: '🌧️',
    category: 'nature',
    description: 'Gentle rainfall',
    color: '#60a5fa',
    glowColor: 'rgba(96,165,250,0.35)',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '🌊',
    category: 'nature',
    description: 'Calm ocean waves',
    color: '#34d399',
    glowColor: 'rgba(52,211,153,0.35)',
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌲',
    category: 'nature',
    description: 'Peaceful woodland',
    color: '#86efac',
    glowColor: 'rgba(134,239,172,0.35)',
  },
  {
    id: 'thunder',
    name: 'Thunder',
    emoji: '⛈️',
    category: 'nature',
    description: 'Distant thunderstorm',
    color: '#a78bfa',
    glowColor: 'rgba(167,139,250,0.35)',
  },
  {
    id: 'fire',
    name: 'Campfire',
    emoji: '🔥',
    category: 'nature',
    description: 'Crackling campfire',
    color: '#fb923c',
    glowColor: 'rgba(251,146,60,0.35)',
  },
  {
    id: 'wind',
    name: 'Wind',
    emoji: '💨',
    category: 'ambient',
    description: 'Gentle breeze',
    color: '#e2e8f0',
    glowColor: 'rgba(226,232,240,0.35)',
  },
  {
    id: 'white-noise',
    name: 'White Noise',
    emoji: '🌫️',
    category: 'ambient',
    description: 'Pure white noise',
    color: '#f8fafc',
    glowColor: 'rgba(248,250,252,0.35)',
  },
  {
    id: 'brown-noise',
    name: 'Brown Noise',
    emoji: '🟤',
    category: 'ambient',
    description: 'Deep low rumble',
    color: '#d97706',
    glowColor: 'rgba(217,119,6,0.35)',
  },
  {
    id: 'night',
    name: 'Night Insects',
    emoji: '🦗',
    category: 'nature',
    description: 'Summer cricket chorus',
    color: '#4ade80',
    glowColor: 'rgba(74,222,128,0.35)',
  },
  {
    id: 'binaural-focus',
    name: 'Focus Beats',
    emoji: '🧠',
    category: 'focus',
    description: 'Alpha binaural beats',
    color: '#f472b6',
    glowColor: 'rgba(244,114,182,0.35)',
  },
  {
    id: 'binaural-relax',
    name: 'Relax Beats',
    emoji: '😴',
    category: 'focus',
    description: 'Theta wave relaxation',
    color: '#818cf8',
    glowColor: 'rgba(129,140,248,0.35)',
  },
  {
    id: 'singing-bowl',
    name: 'Singing Bowl',
    emoji: '🔔',
    category: 'focus',
    description: 'Tibetan bowl harmonics',
    color: '#fbbf24',
    glowColor: 'rgba(251,191,36,0.35)',
  },
]

export const CATEGORIES = {
  nature: { label: 'Nature', description: 'Sounds from the natural world' },
  ambient: { label: 'Ambient', description: 'Steady background ambience' },
  focus: { label: 'Focus & Meditate', description: 'Tones for concentration and meditation' },
} as const
